name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: A-Ahmed-I
          SETTING_JSON: |
            {
              "githubUserName": "A-Ahmed-I",
              "type": "SouthEast",
              "animator": "Bounce",
              "outputBranchName": "main",
              "outputDir": "profile-3d-contrib"
            }
                - name: Commit & Push
      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Generate 3D contribution calendar"
          git push
